language: objective-c
osx_image: xcode63
before_install:
        - brew update
        - brew install carthage
        - carthage update
xcode_project: FixMyMail.xcodeproj
xcode_scheme: FixMyMailTests
